version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./dev.env
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dev.db.env

volumes:
  postgres_data:
