version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "8001:80"
    depends_on:
      - web
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile.prod
    command: gunicorn hero_cities_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./prod.db.env

volumes:
  postgres_data:
  static:
  media:
