# Generated by Django 4.2.3 on 2023-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49, verbose_name='название')),
                ('text', models.TextField(verbose_name='описание')),
                ('lantitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='широта')),
                ('longtitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='долгота')),
            ],
        ),
    ]
