# Generated by Django 4.2.3 on 2023-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='annotation',
            field=models.CharField(max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='city',
            name='new_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Современное изображение'),
        ),
        migrations.AddField(
            model_name='city',
            name='old_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Историческое изображение'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lantitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longtitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
